### PR TITLE
Cumulative update Oct-29-2021

### PR DESCRIPTION
**Pull request by nuald**
* maintenance update with the versions;
* all missing clang tests have been added;
* dropped unmaintained json-stream in Haskell json test;
* LuaJIT has been replaced with OpenResty's that supports more platforms;
* fixed minor issue in C++ tests;
* bumped Rust edition

### CODE REVIEW

**Comment by beached** [comment]
The memory numbers in JSON look off for the check before parsing for the first 5 items

**Comment by nuald** [comment]
Not only those, but some other tests too. Some updates screwed up the tests, e.g. some of C++ tests just occasionally crash despite being complete valid. You could see that I've added sanitizers for testing, it's commented out for production, but I've used those for the debugging. Also, used Valgrind, and it also shows that everything is valid too. I think either Debian testing image or newer docker have some issues, I'm going to look into it soon, and possibly replace both.

However, I can get the memory numbers right away, will fix it, thanks for noticing.

**Comment by nuald** [comment]
Memory numbers fixed in #383

**Comment by kostya** [comment]
missing Primes Zig result.

**Comment by nuald** [comment]
Thanks for noticing, addressed in #384

**Pull request merged**
