### PR TITLE
Improve RapidJSON performance

### PR DESCRIPTION
**Pull request by miloyip**
By using `FileReadStream` instead of C++ iostream converisons, less time was spent in reading the file. Also, provided a SAX version which is faster and cost much less memory.

On my rMBP:
~~~
Original
1.64s, 1031.5Mb

Using FileReadStream
0.75s, 336.3Mb

SAX
0.43s, 0.7Mb
~~~

### CODE REVIEW

**Comment by kostya** [comment]
after update rapidjson repo, 0.79 -> 0.94 (i not updated result for half of year), and sax result is 0.72

**Comment by miloyip** [comment]
I think there should not have commits that affect the performance so much. The results are quite contradictory to the one on my machine. I am curious why an i7 machine performs worse than i5 machine though.

**Comment by miloyip** [comment]
I suspect that maybe SSE was enabled previosly but FileReadStream disables it. And on your box that became a bottleneck. I will try it later.

**Comment by kostya** [comment]
may be different gcc versions?

**Comment by kostya** [comment]
problem in commit https://github.com/miloyip/benchmarks/commit/34f96c2f25556024f9095ddd1536654a23ac632f, if i revert it 0.92 -> 0.72

**Comment by kostya** [comment]
read_file function executed in 0.12 for me.

**Pull request merged**
