### PR TITLE
java base64

### PR DESCRIPTION
**Pull request by w-diesel**
mainly for comparison with scala

### CODE REVIEW

**Comment by w-diesel** [comment]
btw.. please update rust version and crates.

**Comment by kostya** [comment]
```
Base64Java.java:1: error: cannot find symbol
import java.util.Base64;
```

javac -version
javac 1.7.0_67

java -version
java version "1.8.0_45"

**Comment by kostya** [comment]
rust 1.6,1.7,1.8 with updated crates cannot compile json example.

**Comment by w-diesel** [comment]
I checked on rust-nightly, with updated crates, and "json" compiled without any warning.
Maybe you forgot to update crates for "json"?
**cargo update --manifest-path /path/to/Cargo.toml**

rustc 1.8.0-nightly (4b615854f 2016-01-26)
cargo 0.9.0-nightly (6ffd134 2016-01-26)

**Pull request merged**
