### PR TITLE
added Clojure JSON test

### PR DESCRIPTION
**Pull request by yogthos**
One thing to note is that due to the JVM warmup the initial run performance will not be representative of overall performance for a long running process. Normally, you'd do multiple runs with a warmed up JVM using something like [Criterium](https://github.com/hugoduncan/criterium).

### CODE REVIEW

**Comment by kostya** [comment]
thanks, better to wget all this files in build.sh

**Comment by yogthos** [comment]
The proper way to do it would be to use [leiningen](http://leiningen.org/) build tool, if you can set that up, I can package a proper project the way it's done for haskell and rust.

**Comment by kostya** [comment]
would be nice

**Comment by yogthos** [comment]
ok cool just updated the pr to use leiningen

**Pull request closed without merging**
