### PR TITLE
Small header fixes

### PR DESCRIPTION
**Pull request by cwaffles**
- Fixed spacing for time
- Corrected megabit to megabyte (base 2)

### CODE REVIEW

**Comment by kostya** [comment]
hm,

```
MiB = Mebibyte = 1024 KiB
KiB = Kibibyte = 1024 Bytes
MB = Megabyte = 1,000 KB
KB = Kilobyte = 1,000 Bytes
```

and this should be MB, because megabytes

**Comment by cwaffles** [comment]
Linux counts memory usage in base 2, meaning a KiloByte is 1024 bytes.

See this post for example http://www.tecmint.com/check-memory-usage-in-linux/.

The amount of RAM used is 1046147072 bytes. If you want to convert that to Megabytes (base 2), divide by 1024^2. Which is 997.68, which matches the conversions later on.

However if you divide it by SI bytes (base 10), then the result is 1046, which doesn't match the conversions later on.

Networking is base 10, hard drive storage is mixed between base 2 and base 10, and RAM is base 2.

From wikipedia:

> The hardware industry has coped with the dual definitions because of relative consistency: system memory (RAM) typically uses the binary meaning while magnetic disk storage uses the SI meaning. There are, however, exceptions and special cases. Diskettes use yet another "megabyte" equal to 1024×1000 bytes.[37] In optical disks, Compact Disks use MB to mean 10242 bytes while DVDs use GB to mean 10003 bytes.[38][39] -- https://en.wikipedia.org/wiki/Binary_prefix#Operating_systems

**Comment by kostya** [comment]
i measuring like this:
```
ps p 63009 -o rss
  RSS
141736

141736 / 1024.0
=> 138.41 Mb
```

**Comment by cwaffles** [comment]
Yes, which is a MegaByte in base 2. I wrote MiB to avoid confusion between base 2 and base 10 systems.

**Comment by kostya** [comment]
not understand really, but ok

**Pull request merged**
