### PR TITLE
Many improvements to bf.d

### PR DESCRIPTION
**Pull request by JackStouffer**
* Use official D style as described here: https://dlang.org/dstyle.html
* Removed unnecessary calls to `std.conv.to`. In D, `char` implicitly converts to integer types, so no need to cast or convert `0` to `char`. Also, because brainfuck only contains ASCII values, we can safely cast from `int` to `char` with no loss of precision
* Removed semi-colons at the end of classes. These are not needed in D and just result in empty declarations
* Added attributes that allow the compiler to use better code-gen

### CODE REVIEW

**Comment by kostya** [comment]
thanks, somehow after this d from 3th place move to 6th place

**Comment by JackStouffer** [comment]
Odd. Are you using the same compilers with the same arguments?

**Comment by kostya** [comment]
yes

**Comment by kostya** [comment]
and with just switching branches i get difference, so it reproducable:
`old: 184d954e454309ba3edc5b1940862523226a1524, 2.37s, 1.4Mb`
`new: 3ef942d8c71bd0addec5624e4676c13cee441e8e, 3.07s, 1.4Mb`

**Comment by JackStouffer** [comment]
How bizarre. What about the other compilers?

**Comment by kostya** [comment]
https://github.com/kostya/benchmarks/commit/eccc0e54abec04547275b14acc0831996d00d4a8

**Comment by kostya** [comment]
actually only attrs `@safe pure nothrow:` make this change, so i think i revert this commit ca4924432164f8123b144862046410865eb3b093

**Comment by JackStouffer** [comment]
> make this change, so i think i revert this commit ca49244

That would be great :)

**Pull request merged**
