### PR TITLE
Optimization for base64/test.scala (24.71s -> 7.42s on i5-4670)

### PR DESCRIPTION
**Pull request by orionll**
Requires Java 8

### CODE REVIEW

**Comment by kostya** [comment]
how to compile it. i installed java8
```
java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

```
scala -version
Scala code runner version 2.11.6 -- Copyright 2002-2013, LAMP/EPFL
```

```
 scalac test.scala
test.scala:2: error: object Base64 is not a member of package java.util
  val enc = java.util.Base64.getEncoder
                      ^
test.scala:3: error: object Base64 is not a member of package java.util
  val dec = java.util.Base64.getDecoder
                      ^
two errors found
```

**Comment by orionll** [comment]
Run `scala` (with no args). What is your output?

**Comment by kostya** [comment]
Welcome to Scala version 2.11.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_67).

**Comment by orionll** [comment]
What is your JAVA_HOME? If it does not point to Java 8, please, fix it.

**Pull request merged**
