### PR TITLE
add V lang

### PR DESCRIPTION
**Pull request by kostya**
https://github.com/vlang/v

### CODE REVIEW

**Comment by kostya** [comment]
little strange results comparing to mine (`V 0.1.21 2709344`) on my osx notebook, v bf2 2 times slower than crystal and go, mandel.b similar to crystal, base64 2 times slower than crystal, json looks similar, matmul 1.5 times slower than crystal (not 10 times). are you sure you not forget -prod option?

**Comment by nuald** [comment]
I've verified results with macOS with the same language versions as in Ubuntu (with the same build options including "-prod" for V):
- Crystal 0.31.1
- go version go1.13.1
- V 0.1.21 c18578a

My results in macOS are consistent with yours:

Language                  | Ubuntu 18.04.3 LTS  | macOS 10.14.6
-------------------- | -------------------- | --------------
bf2 bench - Crystal  | 3.09s                         | 2.62s
bf2 bench - Go         | 2.65s                         | 2.16s
bf2 bench - V            | 19.40s                       | 6.13s
bf2 mandel - Crystal | 25.16s                       | 21.70s
bf2 mandel - Go        | 47.60s                       | 35.17s
bf2 mandel - V          | 112.51s                       | 25.70s
base64 - Crystal       | 2.11s                           | 1.53s
base64 - Go              | 3.68s                          | 2.87s
base64 - V                | 27.04s                         | 3.74s
json - Crystal            | 4.62s                           | 2.87s
json - Go                   | 3.47s                           | 3.12s
json - V                     | 3.40s                           | 4.77s
matmul - Crystal      | 3.31s                           | 4.21s
matmul - Go             | 3.82s                          | 4.22s
matmul - V               |  41.91s                        | 4.21s

As you can see, V consistently shows the better performance in macOS (except JSON as it uses the C library for that: https://github.com/vlang/v/tree/master/thirdparty/cJSON). Also I've noticed that compilation time for V code is slower in macOS, so I assume it applies better optimizations comparing with Linux:

Code                  | Ubuntu 18.04.3 LTS  | macOS 10.14.6
-------------------- | -------------------- | --------------
bf2 | 0.06s, 2.5Mb                         | 0.98s, 8.9Mb
base64 | 0.09s, 2.4Mb                         | 1.23s, 15.4Mb
json | 0.07s, 2.4Mb                         | 1.01s, 9.4Mb
matmul | 0.07s, 2.5Mb                         | 0.97s, 8.8Mb

So I don't think it's anything wrong with the tests, but rather V is still under development and could have lower priority for GNU/Linux support. I guess we may have a special page for that kind of experiments and use the main page tables for the stable versions of languages only.

**Comment by kostya** [comment]
ok, thanks

**Comment by kostya** [comment]
they suggest that `-cc gcc` compile option should fix ubuntu issues. @nuald can you check?

**Comment by nuald** [comment]
They're absolutely right: v has `-show_c_cmd` options that shows what compiler is used. For macOS it uses `cc` (Clang), and for Linux (I've verified in ArchLinux too) it uses pre-build `tcc` (installed by V itself) that is Tiny C Compiler (https://bellard.org/tcc/, not maintained anymore).

I've verified both `-cc gcc` and `-cc clang` options and the resulted binaries performed much better. I'll submit the new changes soon.

**Pull request merged**
