### PR TITLE
Optimizations for brainfuck/C++; 6.87sec -> 2.90sec on i3-2100T

### PR DESCRIPTION
**Pull request by anttirt**
You can use -DUSE_FOO=0 for any of the four specific optimizations to see how they impact performance.

Tested with g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2

### CODE REVIEW

**Comment by kostya** [comment]
you also change bracket_map to vector :_) 
all implementations used standard language map, so it unfair.
not sure if other changes have any meaning, gcc should optimize other cases by itself. and code is so dirty.

**Comment by anttirt** [comment]
> so it is unfair.

First off, Nim's Table is a hash table; C++ std::map is a red-black tree, but std::unordered_map is also available, so that's already a significant difference in the libraries used. Secondly, I think the benchmark itself is kind of unfair and misleading because the benchmark is not comparing the language or compiler.

The benchmark compares how well the standard library's map/table is optimized for *extremely small maps*; there are only 27 entries in the map.

The other changes do have a small but clear effect as well. With all of them disabled, I get 6.45sec and with only -DUSE_FLAT_MAP=0 I get 6.01sec.

**Comment by kostya** [comment]
i tested unordered_map it was even slower. in rust for example was hash map, but when move to btree it became faster https://github.com/kostya/benchmarks/pull/26.

i don't want to do super hacks to win benchmark. i want to implement algorithm idiomatically (vector is not good, because bf code can be super big), in the same way in different languages, and see, what performance they give. and may be apply little performance tricks.

yes, my way of benchmarking is not fair, but it is what i wanted to measure.

**Comment by anttirt** [comment]
> yes, my way of benchmarking is not fair, but it is what i wanted to measure.

I see. I'd appreciate it if you at least added a comment to the root README.md noting that many of the benchmarks measure library performance and not language/compiler performance.

**Comment by Manishearth** [comment]
> i don't want to do super hacks to win benchmark. i want to implement algorithm idiomatically

This isn't as cut and dry as it sounds. "Idiomatically" is context-sensitive. When there are multiple maps available, the more idiomatic map depends on what you're trying to do.

In Rust's case, for example, [this is explicitly stated in the docs](http://doc.rust-lang.org/std/collections/). When you say "I want a hashmap", that question isn't enough.

What this often does end up benchmarking is what naively written code is like :smile:

**Comment by kostya** [comment]
now there is brainfuck2 benchmark https://github.com/kostya/benchmarks#brainfuck-v20, which not used hash_map at all.

**Pull request closed without merging**
