### PR TITLE
[bf2/D]: Improve performance and code elegance

### PR DESCRIPTION
**Pull request by ZombineDev**
Results:

|        | LDC bench.b           | LDC mandel.b       | GDC bench.b       | GDC mandel.b           | DMD bench.b           | DMD mandel.b       |
|--------|-----------------------|--------------------|-------------------|------------------------|-----------------------|--------------------|
| Before | 2.79s / 1.0Mb         | 36.06s / 2.8Mb     | **2.19s** / 2.8Mb | 31.16s / 3.7Mb         | 5.32s / 1.5Mb         | 79.70s / 3.4Mb     |
| After  | **1.87s** / **0.9Mb** | **22.57s** / 2.8Mb | 2.54s / **2.7Mb** | **27.46s** / **3.5Mb** | **4.92s** / **1.4Mb** | **60.18s** / 3.4Mb |

For reference, here are the C++ results for my machine:

|     | g++ bench.b | g++ mandel.b |
|-----|-------------|--------------|
| C++ | 2.19s / 1.5Mb      | 20.50s / 3.3Mb       |

```
$ g++ -O3 -o bin_cpp bf.cpp && ../xtime.rb ./bin_cpp ./bench.b 
2.19s, 1.5Mb
$ g++ -O3 -o bin_cpp bf.cpp && ../xtime.rb ./bin_cpp ./mandel.b
20.50s, 3.3Mb
```

D results before:
```
$ ldc2 -of bin_d_ldc -O5 -release bf.d && ../xtime.rb ./bin_d_ldc ./bench.b
2.79s, 1.0Mb
$ ldc2 -of bin_d_ldc -O5 -release bf.d && ../xtime.rb ./bin_d_ldc ./mandel.b
36.06s, 2.8Mb

$ gdc-5 -o bin_d_gdc -O3 -frelease -finline bf.d && ../xtime.rb ./bin_d_gdc ./bench.b
2.19s, 2.8Mb
$ gdc-5 -o bin_d_gdc -O3 -frelease -finline bf.d && ../xtime.rb ./bin_d_gdc ./mandel.b
31.16s, 3.7Mb

$ dmd -ofbin_d -O -inline -release bf.d && ../xtime.rb ./bin_d ./bench.b
5.32s, 1.5Mb
$ dmd -ofbin_d -O -inline -release bf.d && ../xtime.rb ./bin_d ./mandel.b
79.70s, 3.4Mb
```

D results after:
```
$ ldc2 -of bin_d_ldc -O5 -release bf.d && ../xtime.rb ./bin_d_ldc ./bench.b
1.87s, 0.9Mb
$ ldc2 -of bin_d_ldc -O5 -release bf.d && ../xtime.rb ./bin_d_ldc ./mandel.b
22.57s, 2.8Mb

$ gdc-5 -o bin_d_gdc -O3 -frelease -finline bf.d && ../xtime.rb ./bin_d_gdc ./bench.b
2.54s, 2.7Mb
$ gdc-5 -o bin_d_gdc -O3 -frelease -finline bf.d && ../xtime.rb ./bin_d_gdc ./mandel.b
27.46s, 3.5Mb

$ dmd -ofbin_d -O -inline -release bf.d && ../xtime.rb ./bin_d ./bench.b
4.92s, 1.4Mb
$ dmd -ofbin_d -O -inline -release bf.d && ../xtime.rb ./bin_d ./mandel.b
60.18s, 3.4Mb
```
(The actual program output is omitted for brevity.)

As you can see, the only regression is GDC bench.b, but apart from that it's a clear improvement across the board.

Some info about the test environment:
```
$ ldc2 --version
LDC - the LLVM D compiler (1.0.0):
  based on DMD v2.070.2 and LLVM 3.8.0
  built with LDC - the LLVM D compiler (1.0.0)
  Default target: x86_64-unknown-linux-gnu
  Host CPU: ivybridge
  http://dlang.org - http://wiki.dlang.org/LDC

  Registered Targets:
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64

$ gdc-5 --version
gdc-5 (Ubuntu 5.3.1-14ubuntu2.1) 5.3.1 20160413
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ --version
g++ (Ubuntu 5.3.1-14ubuntu2.1) 5.3.1 20160413
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ dmd --version
DMD64 D Compiler v2.070.0
Copyright (c) 1999-2015 by Digital Mars written by Walter Bright

$ uname -a
Linux zombinedev-desktop 4.5.0-040500-generic #201603140130 SMP Mon Mar 14 05:32:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ cat /proc/cpuinfo | grep -e "model name" | head -1
model name	: Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz
```

### CODE REVIEW

**Comment by kostya** [comment]
thanks, i ll try it soon, no really understand why it faster now, seems nothing valuable changed

**Comment by ZombineDev** [comment]
Well I tried to keep the algorithm as it is (even though it was hard to resist :D). Most of the changes are:
+ removed everything unnecessary like `StringIterator`
+ made program `Op`s `immutable` (instead of mutable)
+ used static `foreach` to make the dispatch faster in `run`
+ changed classes to structs because polymorphism wasn't needed (everything was `final` before).
+ made `run` and `parse` with arguments static. I would prefer them to be free functions and to remove `Program` all together, but I didn't want to deviate much from the original.

**Comment by ZombineDev** [comment]
Some future optimizations would be:
+ Pre-allocate the tape (e.g. change `int[] tape = [0]` to `int[] tape = new int[1024]`) and reduce moveNext only to `pos++`, but I wasn't sure if this would be a fair. Also it didn't make a big difference: 22.57s vs 21.11s (for LDC, mandel.b)
+ Use `core.stdc.stdio.putchar()` instead of `std.stdio.write()` + `std.stdio.File.flush()` (i.e. disable flushing), but again I wasn't sure if it's fair to disable flushing, and secondly, it didn't bring consistently better results - for some strange reason it was faster only combination with the above optimization (22.57s-> 21.11s -> 20.07s), but it was slower on its own (22.57s->23.47s).

**Comment by ZombineDev** [comment]
I added C++ times for reference to table above.

**Comment by jadbox** [comment]
How did your changes end up reducing the memory footprint?

**Comment by ZombineDev** [comment]
I wouldn't (and don't) advertise that it reduces memory usage, because during testing it was often the case that the results would vary between +/- 0.1MB, though it was relatively stable. As you can see, it depends mostly on the compiler - e.g. newer versions of druntime may have different array growth factors, also memory allocations could be elided by the compiler (I suspect that LDC might be doing that).
My biggest motivation for this change is that the run time is noticeably reduced for the majority of cases (compilers and test cases) and that code is shorter / easier to follow.

**Comment by ZombineDev** [comment]
@jadbox Oh, I forgot to mention, since I changed all classes to structs, those objects are now placed on the stack (instead of the heap), so this surely accounts for some reduction of memory usage, albeit a tiny one. (I'm talking about `Program` and `Tape`.)

**Pull request merged**
