### PR TITLE
Update rust brainfuck with a much more rust-oriented approach

### PR DESCRIPTION
**Pull request by daboross**
This updates brainfuck.rs to use a more rust oriented approach to the rust brainfuck, using an enum to store instructions and loop positions rather than a `Vec<char>` and `HashMap`.

I've tried to keep to the coding style used in the previous file as much as possible while using a more rustic approach to the execution itself.

### CODE REVIEW

**Comment by kostya** [comment]
why close? seems not bad, i can't accept it right now, because other implementations is different, but may be reimplement other tests like this, to remove questions about hash_map, tree_map.

**Comment by daboross** [comment]
I just realized that it would probably be not great to have one program implement it completely differently from the others. I'll reopen if you want to work on changing the other programs to behave like this, although I wouldn't know how to do this in many other languages.

**Comment by kbrock** [comment]
@kostya Are you testing the various languages using the same basic implementation?
Or are you testing idiomatic code?

May want to state your preference.

I did notice a number of multi arrays and thought a single array may be quicker. -- `a[x,y]` vs a[x*WIDTH+y]`, but don't know your preference on this matter.

Would be cheap to implement one way in one language and the other way for another language.

**Comment by dbohdan** [comment]
@kbrock I second your question.

**Pull request closed without merging**
