### PR TITLE
bf.swift: use unsafe buffer pointer to the tape

### PR DESCRIPTION
**Pull request by ricvelozo**
Small optimization similar to the Rust version (7e2fc03).

### CODE REVIEW

**Comment by nuald** [comment]
The numbers are up-to-dated. Please note that the changes are negligible because we use `-Ounchecked` compiler option for Swift.

**Comment by kostya** [comment]
is not this is the same microoptimization like this: https://github.com/kostya/benchmarks/pull/422/files#diff-da22c1257fb473df31008d86b02a973793bdeefe14abe5e9de076a782475868dR45

**Comment by nuald** [comment]
Almost, and if the aforementioned change would only have `[direct_array_access]` added, I think we could merge it (as this approach could be definitely seen in average code). However, another change (`t.tape << [0]`) is definitely a compiler issue as it's not expected that pushing an array is faster than pushing one element.

**Comment by ricvelozo** [comment]
> The numbers are up-to-dated. Please note that the changes are negligible because we use `-Ounchecked` compiler option for Swift.

I think `-Ounchecked` just disables integer overflow checks.

**Pull request merged**
