### PR TITLE
Speedup brainfuck.rb

### PR DESCRIPTION
**Pull request by splattael**
This PR speeds up the runtime of `brainfuck.rb`.

### CODE REVIEW

**Comment by kostya** [comment]
i not see any big speedup, just 6%, so i prefer to leave code more readable, than hackable.

**Comment by splattael** [comment]
@kostya Thanks for trying :)

Strange, I see a speed-up of almost a minute: `3m52s` -> `3m02s`.
Can you provide your numbers, please? :eyeglasses:

**Comment by kostya** [comment]
ruby 2.2.2: 226.86s -> 213.15s
topaz not changed
jruby not changed

**Comment by splattael** [comment]
I'm also using 2.2.2 and I have no idea why it's so different :/

Thank you anyway.

**Pull request closed without merging**
